SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[State] (
		[StateCode]     [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[Descr]         [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [PK__State__D515E98BDFEA2A2F]
		PRIMARY KEY
		CLUSTERED
		([StateCode])
	ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[State] SET (LOCK_ESCALATION = TABLE)
GO
